# -*- coding: utf-8 -*-
"""011171168_TASK B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AVAvTIwCqN6j8O4TCa9znnW7OrY48aiV
"""

import matplotlib.pyplot as plt
import math
import random
r= 8.5

def monte_carlo(trial_no):
  hits = 0
  for i in range(trial_no):
    X_r = random.uniform(-r, r)
    Y_r = random.uniform(0, r)

    dis = math.sqrt(X_r**2 + Y_r**2)

    if dis <= r:
      hits+=1
      
    else :
      pass
      
  pi = ((hits/trial_no)*(8.5*8.5)*4) / (r**2)
  return 3.1416-pi   



X = []
Y= []

for i in range(5):
    trial_no=int(input())
    X.append(trial_no)
    error = monte_carlo(trial_no)
    Y.append(error)


plt.plot(X,Y,'g')
plt.show()